# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

products.page_size = 20
services.page_size = 20

frontend.url = http://localhost:3000
backend.url = http://localhost:8080/TravelBookingSystem

cors.allowed.origins = http://localhost:3000

cloudinary.cloud_name =
cloudinary.api_key =
cloudinary.api_secret =

stripe.secret.key =

paypal.api.base = https://api-m.sandbox.paypal.com
paypal.client.id =
paypal.client.secret =
paypal.vnd.to.usd = 26000

momo.partner.code = MOMO
momo.api.url = https://test-payment.momo.vn/v2/gateway/api/create
momo.access.key =
momo.secret.key =

zalopay.app.id = 2553
zalopay.api.url = https://sb-openapi.zalopay.vn/v2/create
zalopay.key1 =
zalopay.key2 =
