# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

products.page_size = 20
services.page_size = 20

frontend.url = http://localhost:3000
backend.url = http://localhost:8080/TravelBookingSystem

cors.allowed.origins = http://localhost:3000

cloudinary.cloud_name = dlvmrl6g4
cloudinary.api_key = 382554788796221
cloudinary.api_secret = cH2oJwMLa7EvbMytwEamYqexYNE

stripe.secret.key = sk_test_51TNcDPDyUFunJoca1pyb1UAgFK9VJH64ZP06H9InKgVnYE7QQJduGdCY7JAQTsG01VI8JirEnTpBmTlxPD1rEBnp00GwMXMJQa

paypal.api.base = https://api-m.sandbox.paypal.com
paypal.client.id = AdEV1W4Og02FZLMB57RSCy57Sqi0M0aLJ-dNr4PGMomrzFbXiwJ_YeN1yC_lvZ5yWSLPFhSnWUXMRwCV
paypal.client.secret = EBynJlAF402FCzKIpg3mzwRajJxd_JnigDei64zKbTSm7xDtQ_nkHYfyL-Ju_3vbtLnxq9ZhU3-XjsTX
paypal.vnd.to.usd = 26000

momo.partner.code = MOMO
momo.api.url = https://test-payment.momo.vn/v2/gateway/api/create
momo.access.key = F8BBA842ECF85
momo.secret.key = K951B6PE1waDMi640xX08PD3vg6EkVlz

zalopay.app.id = 2553
zalopay.api.url = https://sb-openapi.zalopay.vn/v2/create
zalopay.key1 = PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
zalopay.key2 = kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz
