const travelChatStyles = {
    launcher: {
        position: "fixed",
        right: 24,
        bottom: 24,
        height: 48,
        padding: "0 18px",
        borderRadius: 8,
        border: "1px solid #2563eb",
        background: "#fff",
        color: "#2563eb",
        display: "inline-flex",
        alignItems: "center",
        gap: 8,
        fontWeight: 750,
        boxShadow: "0 8px 20px rgba(15, 23, 42, 0.12)",
        zIndex: 1200,
    },
    panel: {
        position: "fixed",
        right: 24,
        top: 112,
        width: 840,
        maxWidth: "calc(100vw - 32px)",
        height: "calc(100vh - 136px)",
        maxHeight: 620,
        minHeight: 520,
        background: "#fff",
        border: "1px solid #e2e8f0",
        borderRadius: 8,
        boxShadow: "0 12px 34px rgba(15, 23, 42, 0.14)",
        display: "grid",
        gridTemplateColumns: "320px minmax(0, 1fr)",
        overflow: "hidden",
        zIndex: 1200,
    },
    sidebar: {
        borderRight: "1px solid #e2e8f0",
        display: "flex",
        flexDirection: "column",
        minWidth: 0,
    },
    sidebarHeader: {
        height: 52,
        padding: "0 14px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottom: "1px solid #e2e8f0",
        color: "#0f172a",
        fontWeight: 800,
    },
    headerButton: {
        width: 32,
        height: 32,
        borderRadius: "50%",
        border: 0,
        background: "#f1f5f9",
        color: "#334155",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
    },
    searchBox: {
        padding: 10,
        borderBottom: "1px solid #e2e8f0",
    },
    searchInput: {
        width: "100%",
        border: "1px solid #dbe3ef",
        borderRadius: 8,
        padding: "8px 10px",
        outline: "none",
        fontSize: 14,
    },
    roomList: {
        flex: 1,
        overflowY: "auto",
    },
    roomItem: active => ({
        width: "100%",
        border: 0,
        borderBottom: "1px solid #f1f5f9",
        background: active ? "#f8fafc" : "#fff",
        padding: 12,
        textAlign: "left",
        cursor: "pointer",
        display: "flex",
        gap: 10,
    }),
    avatar: {
        width: 42,
        height: 42,
        borderRadius: "50%",
        background: "#eff6ff",
        color: "#2563eb",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flex: "0 0 auto",
        fontWeight: 800,
    },
    roomMeta: {
        minWidth: 0,
        flex: 1,
    },
    roomTop: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 8,
    },
    roomName: {
        color: "#0f172a",
        fontWeight: 750,
        overflow: "hidden",
        whiteSpace: "nowrap",
        textOverflow: "ellipsis",
    },
    roomTime: {
        color: "#94a3b8",
        fontSize: 12,
        flex: "0 0 auto",
    },
    roomService: {
        color: "#64748b",
        fontSize: 13,
        overflow: "hidden",
        whiteSpace: "nowrap",
        textOverflow: "ellipsis",
        marginTop: 2,
    },
    roomLast: {
        color: "#94a3b8",
        fontSize: 13,
        overflow: "hidden",
        whiteSpace: "nowrap",
        textOverflow: "ellipsis",
        marginTop: 2,
    },
    chat: {
        display: "flex",
        flexDirection: "column",
        minWidth: 0,
    },
    chatHeader: {
        height: 52,
        padding: "0 16px",
        borderBottom: "1px solid #e2e8f0",
        display: "flex",
        alignItems: "center",
        gap: 10,
    },
    chatTitle: {
        color: "#0f172a",
        fontWeight: 800,
    },
    chatSub: {
        color: "#64748b",
        fontSize: 13,
    },
    messages: {
        flex: 1,
        padding: 16,
        overflowY: "auto",
        background: "#f8fafc",
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    empty: {
        margin: "auto",
        color: "#64748b",
        textAlign: "center",
        lineHeight: 1.5,
        maxWidth: 320,
    },
    messageWrap: mine => ({
        alignSelf: mine ? "flex-end" : "flex-start",
        maxWidth: "76%",
    }),
    sender: {
        color: "#64748b",
        fontSize: 12,
        fontWeight: 700,
        marginBottom: 4,
    },
    bubble: mine => ({
        padding: "9px 12px",
        borderRadius: mine ? "12px 12px 4px 12px" : "12px 12px 12px 4px",
        background: mine ? "#2563eb" : "#fff",
        color: mine ? "#fff" : "#0f172a",
        border: mine ? "none" : "1px solid #e2e8f0",
        boxShadow: "none",
        whiteSpace: "pre-wrap",
        overflowWrap: "anywhere",
    }),
    msgTime: mine => ({
        color: "#94a3b8",
        fontSize: 12,
        marginTop: 4,
        textAlign: mine ? "right" : "left",
    }),
    inputRow: {
        padding: 12,
        borderTop: "1px solid #e2e8f0",
        display: "flex",
        gap: 10,
        background: "#fff",
        alignItems: "flex-end",
    },
    input: {
        flex: 1,
        minHeight: 42,
        maxHeight: 92,
        resize: "none",
        border: "1px solid #cbd5e1",
        borderRadius: 8,
        padding: "9px 11px",
        outline: "none",
    },
    send: {
        width: 42,
        height: 42,
        border: 0,
        borderRadius: 8,
        background: "#2563eb",
        color: "#fff",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
    },
    responsive: `
        @media (max-width: 768px) {
            .travel-chat-panel {
                right: 8px !important;
                top: 72px !important;
                width: calc(100vw - 16px) !important;
                height: calc(100vh - 88px) !important;
                min-height: 0 !important;
                grid-template-columns: 1fr !important;
            }
            .travel-chat-sidebar-hidden {
                display: none !important;
            }
        }
    `,
};

export default travelChatStyles;
