const providerStatsStyles = {
    page: {
        marginTop: 28,
        marginBottom: 48,
    },
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-end",
        gap: 16,
        flexWrap: "wrap",
        marginBottom: 18,
    },
    title: {
        fontSize: 32,
        fontWeight: 750,
        color: "#0f172a",
        margin: 0,
    },
    subtitle: {
        color: "#64748b",
        marginTop: 6,
        marginBottom: 0,
    },
    card: {
        border: "1px solid #e2e8f0",
        borderRadius: 10,
        boxShadow: "0 10px 26px rgba(15, 23, 42, 0.06)",
    },
    metricLabel: {
        color: "#64748b",
        fontSize: 15,
        marginBottom: 8,
    },
    metricValue: {
        fontSize: 26,
        fontWeight: 800,
        margin: 0,
    },
    toolbar: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        flexWrap: "wrap",
        marginBottom: 16,
    },
    periodButtons: {
        display: "flex",
        gap: 8,
        flexWrap: "wrap",
    },
    tableTitle: {
        fontSize: 22,
        fontWeight: 750,
        color: "#0f172a",
        marginBottom: 14,
    },
    progressTrack: {
        height: 8,
        borderRadius: 999,
        background: "#e2e8f0",
        overflow: "hidden",
        minWidth: 120,
    },
    progressFill: {
        height: "100%",
        background: "#2563eb",
        borderRadius: 999,
    },
    emptyChart: {
        minHeight: 180,
        border: "1px dashed #cbd5e1",
        borderRadius: 10,
        background: "#f8fafc",
        color: "#64748b",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "column",
        gap: 10,
    },
    emptyIcon: {
        fontSize: 30,
        color: "#94a3b8",
    },
    verticalChart: {
        minHeight: 280,
        padding: "18px 10px 6px",
        border: "1px solid #e2e8f0",
        borderRadius: 10,
        background: "linear-gradient(180deg, #f8fafc 0%, #ffffff 100%)",
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(72px, 1fr))",
        gap: 12,
        alignItems: "end",
    },
    verticalItem: {
        minWidth: 64,
        height: 236,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: 8,
    },
    verticalValue: {
        minHeight: 18,
        color: "#0f172a",
        fontSize: 12,
        fontWeight: 700,
        textAlign: "center",
        whiteSpace: "nowrap",
    },
    verticalBarWrap: {
        width: "100%",
        maxWidth: 48,
        height: 150,
        borderRadius: 12,
        background: "#dbeafe",
        display: "flex",
        alignItems: "flex-end",
        overflow: "hidden",
    },
    verticalBar: {
        width: "100%",
        minHeight: 6,
        borderRadius: "12px 12px 0 0",
        background: "linear-gradient(180deg, #2563eb 0%, #0ea5e9 100%)",
        transition: "height 0.2s ease",
    },
    verticalLabel: {
        minHeight: 34,
        color: "#475569",
        fontSize: 13,
        fontWeight: 650,
        textAlign: "center",
    },
    serviceChart: {
        padding: 18,
        border: "1px solid #e2e8f0",
        borderRadius: 10,
        background: "#f8fafc",
        display: "flex",
        flexDirection: "column",
        gap: 14,
    },
    serviceChartRow: {
        display: "grid",
        gridTemplateColumns: "minmax(180px, 34%) 1fr",
        gap: 14,
        alignItems: "center",
    },
    serviceChartLabel: {
        color: "#0f172a",
        fontWeight: 700,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    serviceBarArea: {
        display: "grid",
        gridTemplateColumns: "1fr minmax(120px, auto)",
        gap: 12,
        alignItems: "center",
    },
    serviceBarTrack: {
        height: 26,
        borderRadius: 999,
        background: "#dbeafe",
        overflow: "hidden",
    },
    serviceBarFill: {
        height: "100%",
        minWidth: 8,
        borderRadius: 999,
        background: "linear-gradient(90deg, #2563eb 0%, #06b6d4 100%)",
        transition: "width 0.2s ease",
    },
    serviceChartValue: {
        color: "#0f172a",
        fontWeight: 750,
        textAlign: "right",
        whiteSpace: "nowrap",
    },
};

export default providerStatsStyles;
