const profileStyles = {
    page: {
        padding: "32px 0 56px",
    },
    header: {
        display: "flex",
        alignItems: "flex-end",
        justifyContent: "space-between",
        gap: 24,
        marginBottom: 24,
    },
    kicker: {
        color: "#2563eb",
        fontSize: 14,
        fontWeight: 700,
        marginBottom: 6,
        textTransform: "uppercase",
    },
    title: {
        color: "#0f172a",
        fontSize: 34,
        fontWeight: 750,
        margin: 0,
    },
    subtitle: {
        color: "#64748b",
        fontSize: 16,
        margin: "8px 0 0",
    },
    primaryButton: {
        minWidth: 132,
        height: 44,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        fontWeight: 650,
    },
    summaryCard: {
        border: "1px solid #e2e8f0",
        borderRadius: 10,
        padding: 28,
        background: "#fff",
        boxShadow: "none",
        minHeight: "100%",
    },
    avatarWrap: {
        position: "relative",
        width: 168,
        height: 168,
        margin: "0 auto 20px",
    },
    avatar: {
        width: 168,
        height: 168,
        objectFit: "cover",
        border: "4px solid #f8fafc",
        boxShadow: "none",
    },
    avatarFallback: {
        width: 168,
        height: 168,
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#eff6ff",
        color: "#2563eb",
        fontSize: 56,
        border: "4px solid #f8fafc",
    },
    avatarButton: {
        position: "absolute",
        right: 10,
        bottom: 12,
        width: 42,
        height: 42,
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#2563eb",
        color: "#fff",
        border: "3px solid #fff",
        cursor: "pointer",
        margin: 0,
        boxShadow: "none",
    },
    name: {
        color: "#0f172a",
        fontSize: 24,
        fontWeight: 750,
        textAlign: "center",
        margin: 0,
    },
    username: {
        color: "#64748b",
        textAlign: "center",
        margin: "6px 0 16px",
    },
    badgeRow: {
        display: "flex",
        flexWrap: "wrap",
        justifyContent: "center",
        gap: 8,
        marginBottom: 22,
    },
    infoList: {
        display: "grid",
        gap: 12,
        marginTop: 18,
    },
    infoItem: {
        display: "flex",
        alignItems: "center",
        gap: 12,
        color: "#334155",
        fontSize: 15,
        overflowWrap: "anywhere",
    },
    formCard: {
        border: "1px solid #e2e8f0",
        borderRadius: 10,
        padding: 28,
        background: "#fff",
        boxShadow: "none",
    },
    formTitleRow: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 16,
        marginBottom: 22,
    },
    formTitle: {
        color: "#0f172a",
        fontSize: 24,
        fontWeight: 750,
        margin: 0,
    },
    formHint: {
        color: "#64748b",
        margin: "6px 0 0",
    },
    actionRow: {
        display: "flex",
        gap: 10,
        flexWrap: "wrap",
        justifyContent: "flex-end",
    },
};

export default profileStyles;
