const adminDashboardStyles = {
    page: {
        marginTop: 28,
        marginBottom: 56,
    },
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-end",
        gap: 20,
        flexWrap: "wrap",
        marginBottom: 22,
        padding: "26px 28px",
        borderRadius: 18,
        border: "1px solid #dbeafe",
        background: "linear-gradient(135deg, #eff6ff 0%, #ffffff 55%, #f5f3ff 100%)",
    },
    eyebrow: {
        color: "#2563eb",
        fontSize: 12,
        fontWeight: 800,
        letterSpacing: "0.14em",
        marginBottom: 8,
    },
    title: {
        fontSize: 34,
        fontWeight: 800,
        color: "#0f172a",
        margin: 0,
    },
    subtitle: {
        color: "#64748b",
        marginTop: 8,
        marginBottom: 0,
        maxWidth: 720,
    },
    card: {
        border: "1px solid #e2e8f0",
        borderRadius: 14,
        boxShadow: "0 8px 24px rgba(15, 23, 42, 0.04)",
    },
    metricLabel: {
        color: "#64748b",
        fontSize: 14,
        fontWeight: 600,
        marginBottom: 8,
        minHeight: 42,
        paddingRight: 52,
    },
    metricBody: {
        position: "relative",
        minWidth: 0,
        padding: 16,
    },
    metricValue: {
        fontSize: "clamp(20px, 1.25vw, 24px)",
        fontWeight: 800,
        margin: 0,
        whiteSpace: "nowrap",
        lineHeight: 1.2,
    },
    iconBox: {
        width: 44,
        height: 44,
        borderRadius: 12,
        display: "grid",
        placeItems: "center",
        fontSize: 19,
        position: "absolute",
        top: 16,
        right: 16,
    },
    toolbar: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 16,
        flexWrap: "wrap",
        marginBottom: 20,
    },
    tableTitle: {
        fontSize: 21,
        fontWeight: 750,
        color: "#0f172a",
    },
    progressTrack: {
        height: 9,
        borderRadius: 999,
        background: "#e2e8f0",
        overflow: "hidden",
        minWidth: 120,
    },
    progressFill: {
        height: "100%",
        background: "linear-gradient(90deg, #2563eb, #7c3aed)",
        borderRadius: 999,
    },
};

export default adminDashboardStyles;